# Generated by Django 4.2.13 on 2026-05-21 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('role', models.CharField(choices=[('guest', 'Гость'), ('employee', 'Сотрудник предприятия'), ('guard', 'Охранник'), ('admin', 'Администратор')], default='guest', max_length=20, verbose_name='Роль')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Заблокирован')),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('pass_id', models.AutoField(primary_key=True, serialize=False)),
                ('qr_code', models.CharField(max_length=255, unique=True, verbose_name='QR-код')),
                ('pdf_file_path', models.CharField(blank=True, max_length=512, verbose_name='Путь к PDF')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Выдан')),
                ('expires_at', models.DateTimeField(verbose_name='Действителен до')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
            ],
            options={
                'verbose_name': 'Пропуск',
                'verbose_name_plural': 'Пропуска',
                'db_table': 'passes',
            },
        ),
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('check_time', models.DateTimeField(auto_now_add=True, verbose_name='Время проверки')),
                ('result', models.CharField(choices=[('allowed', 'Допущен'), ('denied', 'Отказ')], max_length=10, verbose_name='Результат')),
                ('deny_reason', models.TextField(blank=True, verbose_name='Причина отказа')),
                ('guard', models.ForeignKey(limit_choices_to={'role': 'guard'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_visits', to=settings.AUTH_USER_MODEL, verbose_name='Охранник')),
                ('pass_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_logs', to='api.pass', verbose_name='Пропуск')),
            ],
            options={
                'verbose_name': 'Запись журнала посещений',
                'verbose_name_plural': 'Журнал посещений',
                'db_table': 'visit_logs',
                'ordering': ['-check_time'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('setting_id', models.AutoField(primary_key=True, serialize=False)),
                ('pass_validity_hours', models.PositiveIntegerField(default=24, verbose_name='Срок действия пропуска (ч)')),
                ('notification_template_approved', models.TextField(default='Ваша заявка #{request_id} одобрена. Скачайте пропуск в личном кабинете.', verbose_name='Шаблон: одобрение')),
                ('notification_template_rejected', models.TextField(default='Ваша заявка #{request_id} отклонена. Причина: {reason}', verbose_name='Шаблон: отказ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('updated_by', models.ForeignKey(limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_settings', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Настройки системы',
                'verbose_name_plural': 'Настройки системы',
                'db_table': 'system_settings',
            },
        ),
        migrations.CreateModel(
            name='PassRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('visit_purpose', models.TextField(verbose_name='Цель визита')),
                ('visit_date', models.DateField(verbose_name='Дата визита')),
                ('visit_time', models.TimeField(verbose_name='Время визита')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('employee', models.ForeignKey(limit_choices_to={'role': 'employee'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_as_employee', to=settings.AUTH_USER_MODEL, verbose_name='Принимающий сотрудник')),
                ('guest', models.ForeignKey(limit_choices_to={'role': 'guest'}, on_delete=django.db.models.deletion.CASCADE, related_name='requests_as_guest', to=settings.AUTH_USER_MODEL, verbose_name='Гость')),
            ],
            options={
                'verbose_name': 'Заявка на пропуск',
                'verbose_name_plural': 'Заявки на пропуск',
                'db_table': 'pass_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pass',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pass_obj', to='api.passrequest', verbose_name='Заявка'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('approved', 'Заявка одобрена'), ('rejected', 'Заявка отклонена'), ('cancelled', 'Заявка отменена'), ('reminder', 'Напоминание')], max_length=20, verbose_name='Тип')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='Доставлено')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.passrequest', verbose_name='Заявка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'db_table': 'notifications',
            },
        ),
    ]
